"""Give every daily show page a nav that tracks the section you are reading.

Several of these pages are generated by other repositories, so this runs as a
repeatable, idempotent post-step: re-run it after any page is regenerated.

    python scripts/add_nav_scrollspy.py            # patch, then report
    python scripts/add_nav_scrollspy.py --check    # report only, non-zero if stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DAILY = ROOT / 'content/daily'
MARKER = 'data-nav-scrollspy'

# Picks the section whose top has passed just under the sticky nav, clamps to the
# last one at the foot of the page, falls back to the most visible section when
# nothing has cleared the band, and keeps the active tab inside a nav that scrolls
# horizontally on narrow screens.
SCRIPT = '''<script ''' + MARKER + '''>
(()=>{'use strict';
const nav=document.querySelector('nav.nav,nav.chapter-nav,nav');
if(!nav)return;
const links=[...nav.querySelectorAll('a[href^="#"]')];
if(links.length<2)return;
const targets=links.map(a=>{try{return document.getElementById(decodeURIComponent(a.getAttribute('href').slice(1)))}catch(e){return null}});
if(targets.filter(Boolean).length<2)return;
let scroller=links[0].parentElement;
while(scroller&&scroller!==document.body&&scroller.scrollWidth-scroller.clientWidth<=4)scroller=scroller.parentElement;
if(!scroller||scroller===document.body)scroller=null;
let active=-1;
const apply=i=>{
 if(i===active)return;
 active=i;
 links.forEach((a,k)=>{
  const on=k===i;
  a.classList.toggle('active',on);
  if(on)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');
 });
 if(scroller&&i>=0){
  const a=links[i],left=a.offsetLeft,right=left+a.offsetWidth;
  if(left<scroller.scrollLeft)scroller.scrollTo({left:Math.max(0,left-16),behavior:'smooth'});
  else if(right>scroller.scrollLeft+scroller.clientWidth)scroller.scrollTo({left:right-scroller.clientWidth+16,behavior:'smooth'});
 }
};
const px=v=>{const n=parseFloat(v);return Number.isFinite(n)?n:0};
// A section lands under the sticky nav, and scroll-padding / scroll-margin push
// it further down, so the band has to clear whichever offset is largest.
let offsets=[];
const measure=()=>{
 const pad=px(getComputedStyle(document.documentElement).scrollPaddingTop);
 offsets=targets.map(t=>t?Math.max(pad,px(getComputedStyle(t).scrollMarginTop)):0);
};
const pick=()=>{
 const navBottom=Math.max(0,nav.getBoundingClientRect().bottom);
 let i=-1,best=-1,bestArea=0;
 targets.forEach((t,k)=>{
  if(!t)return;
  const box=t.getBoundingClientRect();
  if(box.top<=Math.max(navBottom,offsets[k])+12)i=k;
  const area=Math.min(box.bottom,innerHeight)-Math.max(box.top,navBottom);
  if(area>bestArea){bestArea=area;best=k}
 });
 // At the very foot of the page the last tab always wins, otherwise a short
 // final section could never be reached. Elsewhere, when no section has cleared
 // the band yet, fall back to whichever one fills most of the screen.
 if(Math.ceil(innerHeight+scrollY)>=document.documentElement.scrollHeight-2)
  for(let k=targets.length-1;k>=0;k--)if(targets[k]){i=k;break}
 apply(i>=0?i:(best>=0?best:targets.findIndex(Boolean)));
};
measure();
let queued=false;
const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;pick()})};
addEventListener('scroll',schedule,{passive:true});
addEventListener('resize',()=>{measure();schedule()});
addEventListener('hashchange',schedule);
pick();
})();
</script>
'''

# Pages that already style an active nav link keep their own look; the rest get a
# rule that matches the theme they are built on.
PAPER = ('<style ' + MARKER + '>.nav a.active{color:var(--teal);font-weight:600;'
         'box-shadow:inset 0 -2px 0 var(--teal)}</style>\n')
DARK = ('<style ' + MARKER + '>nav a.active{color:var(--ink);border-color:var(--accent);'
        'background:rgba(255,255,255,.06)}</style>\n')

PAGES = {
    '2026-07-08.show.html': DARK,
    '2026-07-31.show.html': None,
    '2026-08-01.show.html': None,
    '2026-08-02.show.html': None,
    '2026-08-04.show.html': None,
    '2026-08-07.show.html': None,
    '2026-09-06.show.html': PAPER,
    '2026-09-07.show.html': PAPER,
    '2026-09-16.show.html': PAPER,
    '2026-09-18.show.html': PAPER,
}

# 2026-08-07 shipped its own observer. Its band never lights the last section and
# fights a second listener, so it is removed in favour of the shared one.
SUPERSEDED = (
    "const sections=$$('section[id]'),links=$$('.nav a');"
    "const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{"
    "if(entry.isIntersecting){links.forEach(a=>a.classList.toggle('active',"
    "a.getAttribute('href')===`#${entry.target.id}`))}}),"
    "{rootMargin:'-30% 0px -60% 0px'});sections.forEach(s=>observer.observe(s))"
)


def strip(html: str) -> str:
    """Remove a block injected by an earlier version so re-running stays clean."""
    for tag in ('script', 'style'):
        opening = f'<{tag} {MARKER}>'
        while opening in html:
            start = html.index(opening)
            end = html.index(f'</{tag}>', start) + len(f'</{tag}>')
            html = html[:start] + html[end:].lstrip('\n')
    return html


def render(html: str, css: str | None, name: str) -> str:
    """The page as it should look: any earlier block removed, current one applied."""
    html = strip(html).replace(SUPERSEDED, '')
    if '</body>' not in html:
        raise SystemExit(f'{name}: no </body> to anchor the script')
    if css:
        if '</head>' not in html:
            raise SystemExit(f'{name}: no </head> to anchor the style')
        html = html.replace('</head>', css + '</head>', 1)
    return html.replace('</body>', SCRIPT + '</body>', 1)


def patch(path: Path, css: str | None) -> str:
    original = path.read_text(encoding='utf-8')
    updated = render(original, css, path.name)
    if updated == original:
        return 'ok'
    path.write_text(updated, encoding='utf-8')
    return 'patched'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for name, css in sorted(PAGES.items()):
        path = DAILY / name
        if not path.exists():
            print(f'{name:26s} missing')
            continue
        if args.check:
            current = path.read_text(encoding='utf-8')
            state = 'ok' if render(current, css, name) == current else 'STALE'
            if state == 'STALE':
                stale.append(name)
        else:
            state = patch(path, css)
        print(f'{name:26s} {state}')
    if stale:
        print(f'\n{len(stale)} page(s) need `python scripts/add_nav_scrollspy.py`')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
