'use strict';
(async()=>{
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function unpack(encoded){return JSON.parse(await new Response(new Blob([Uint8Array.from(atob(encoded),c=>c.charCodeAt(0))]).stream().pipeThrough(new DecompressionStream('gzip'))).text())}
const D=await unpack($('report-gzip').textContent.trim()),P=JSON.parse($('proof-data').textContent),F=D.factors,defs=D.definitions;
const waiting=new Map(),loaded=new Map(),assetBase=new URL(location.protocol==='about:'?'assets/raw-bank-2026-09-16/factors/':'../assets/raw-bank-2026-09-16/factors/',document.baseURI);
window.rawbankFactorLoaded=async(key,encoded)=>{try{const result=await unpack(encoded);loaded.set(key,result);waiting.get(key)?.resolve(result)}catch(error){waiting.get(key)?.reject(error)}};
const alias=f=>f.metadata.factor_id.split('__')[0],definition=f=>defs[alias(f)]||{},name=f=>definition(f).name||alias(f);
async function loadFactor(i){const f=F[i],key=alias(f)+'__'+f.metadata.projection;if(loaded.has(key))return loaded.get(key);if(!waiting.has(key)){let resolve,reject;const promise=new Promise((ok,fail)=>{resolve=ok;reject=fail});waiting.set(key,{promise,resolve,reject});const script=document.createElement('script');script.src=new URL(key+'.js',assetBase);script.onerror=()=>reject(new Error('因子数据无法加载：'+key));document.head.append(script)}return waiting.get(key).promise}
window.rawbankReport={data:D,proof:P};
const fmt=(v,n=5)=>v===null||v===undefined||!Number.isFinite(v)?'—':Number(v).toFixed(n),comma=v=>Number(v).toLocaleString('en-US'),bp=v=>Number.isFinite(v)?v*1e4:null;
const layers={L1:'基础评分投影',L2:'多证据共识',L3:'微观结构情境',L4:'窗口状态',L5:'用途与流动性机制',L1_diagnostic:'市场行为诊断'},sides={buy:'Buy · 买侧',sell:'Sell · 卖侧',total:'总量诊断'};
const searchText=f=>[name(f),definition(f).description,...Object.values(f.metadata)].join(' ').toLowerCase(),title=f=>name(f)+' · '+sides[f.metadata.projection],periodName=p=>p.id==='full'?'全部 601 日':p.id;
let current=F.map((_,i)=>i).filter(i=>!F[i].diagnostic).sort((a,b)=>Math.abs(F[b].periods[0].ic[1][0]||0)-Math.abs(F[a].periods[0].ic[1][0]||0))[0];
let selection={kind:'leaf',key:current},detailPeriod=0,tab='ic',dateRange={start:D.dates[0],end:D.dates.at(-1)},detailVersion=0,observer,zoomURL;
const collapsed=new Set(),dailyRefresh=new Set(),colors=['#b24f35','#087b78'];
function csv(rows){return '\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n')}
function save(text,filename,type='application/json;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function table(head,rows){return '<table><thead><tr>'+head.map(v=>'<th>'+v+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function options(el,values){el.innerHTML=values.map(([v,t])=>'<option value="'+esc(v)+'">'+esc(t)+'</option>').join('')}
for(const id of ['global-period','detail-period'])options($(id),D.periods.map((p,i)=>[i,periodName(p)]));
for(const [key,label] of Object.entries(layers))$('layer-filter').insertAdjacentHTML('beforeend','<option value="'+key+'">'+key+' · '+label+'</option>');
for(const id of [...new Set(F.map(alias))])$('family-filter').insertAdjacentHTML('beforeend','<option value="'+esc(id)+'">'+esc(id.split('_')[0]+' · '+name(F.find(f=>alias(f)===id)))+'</option>');
function sortIndexes(indexes,key,p){const val=i=>{const s=F[i].periods[p];let v=key.startsWith('ic')?s.ic[0][0]:key==='t'?s.ic[1][3]:key.startsWith('spread')?s.spread[0][0]:s.ic[1][0];return Number.isFinite(v)?(['rank','ic_abs','t','spread'].includes(key)?Math.abs(v):v):-Infinity};return [...indexes].sort((a,b)=>(key==='id'?0:val(b)-val(a))||a-b)}
function scopeMatches(f,scope){return scope==='all'||(scope==='diagnostic')===f.diagnostic}
function rowsForResults(){const p=+$('global-period').value,q=$('result-search').value.trim().toLowerCase(),scope=$('result-scope').value;return sortIndexes(F.map((_,i)=>i).filter(i=>scopeMatches(F[i],scope)&&searchText(F[i]).includes(q)),$('result-sort').value,p)}
const rankingHeaders=['正式列 / 定义','方向','IC','Rank IC','ICIR','Rank NW t','G10−G1 / bp','组差 NW t','有效日'];
function rankingCells(i,p){const f=F[i],s=f.periods[p];return ['<button class="factor-link" data-open="'+i+'"><code>'+esc(alias(f))+'</code></button><small>'+esc(name(f))+(f.diagnostic?' · 诊断':'')+'</small>',esc(sides[f.metadata.projection]),fmt(s.ic[0][0],6),fmt(s.ic[1][0],6),fmt(s.ic[1][5],3),fmt(s.ic[1][3],3),fmt(bp(s.spread[0][0]),3),fmt(s.spread[0][3],3),s.ic[1][4]]}
function bindRanking(root,p){root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=+b.dataset.open;selection={kind:'leaf',key:current};detailPeriod=p;$('detail-period').value=p;dateRange={start:D.periods[p].start,end:D.periods[p].end};if(!filtered().includes(current))resetFilters(false);refresh();$('scope-summary').scrollIntoView({block:'start'})})}
function renderResults(){const indexes=rowsForResults(),p=+$('global-period').value;$('result-note').textContent=periodName(D.periods[p])+' · '+indexes.length+' 列。t 值未经多重比较调整；G10−G1 保留原始方向。';$('all-results').innerHTML=table(rankingHeaders,indexes.map(i=>rankingCells(i,p)));bindRanking($('all-results'),p)}
function filtered(){const layer=$('layer-filter').value,family=$('family-filter').value,side=$('view-mode').value==='all'?'all':$('side-filter').value,q=$('factor-search').value.trim().toLowerCase(),scope=$('factor-scope').value;return F.map((_,i)=>i).filter(i=>{const f=F[i];return (layer==='all'||f.metadata.layer===layer)&&(family==='all'||alias(f)===family)&&(side==='all'||f.metadata.projection===side)&&scopeMatches(f,scope)&&searchText(f).includes(q)})}
function ordered(){const cs=sortIndexes(filtered(),$('factor-sort').value,detailPeriod);if($('factor-arrangement').value==='flat')return cs;return Object.keys(layers).flatMap(layer=>{const group=cs.filter(i=>F[i].metadata.layer===layer);return [...new Set(group.map(i=>alias(F[i])))].flatMap(id=>group.filter(i=>alias(F[i])===id).sort((a,b)=>a-b))})}
function inScope(i){return selection.kind==='leaf'?i===selection.key:selection.kind==='definition'?alias(F[i])===selection.key:F[i].metadata.layer===selection.key}
function metric(v){return '<span class="metric-value '+(v>0?'rank-positive':v<0?'rank-negative':'')+'">'+(v>0?'+':'')+fmt(v,6)+'</span>'}
function branch(kind,key,label,count){return '<summary><button class="tree-toggle" aria-label="展开或收起 '+esc(label)+'">▸</button><button class="tree-title" data-kind="'+kind+'" data-key="'+esc(key)+'" aria-pressed="'+(selection.kind===kind&&selection.key===key)+'">'+esc(label)+'<small>'+count+' 个方向因子</small></button></summary>'}
function factorButton(i){const f=F[i],s=f.periods[detailPeriod],flat=$('factor-arrangement').value==='flat';return '<button class="factor-item '+(selection.kind==='leaf'&&i===current?'active':'')+'" data-index="'+i+'"><span>'+esc(flat?alias(f)+' · '+sides[f.metadata.projection]:sides[f.metadata.projection])+(flat?'<small>'+esc(name(f))+'</small>':'')+'</span>'+metric(s.ic[0][0])+metric(s.ic[1][0])+'</button>'}
function renderList(){const cs=ordered(),flat=$('factor-arrangement').value==='flat';$('factor-count').textContent=cs.length+' / 288 个方向因子';$('side-control').hidden=$('view-mode').value==='all';$('navigation-description').textContent=flat?'全部符合筛选条件的方向因子 · 混排':'研究逻辑 → 具体定义 → Buy / Sell';document.querySelector('.tree-controls').hidden=flat;
 $('factor-list').innerHTML=flat?cs.map(factorButton).join(''):Object.entries(layers).map(([layer,label])=>{const group=cs.filter(i=>F[i].metadata.layer===layer);if(!group.length)return '';return '<details class="factor-logic" data-branch="'+layer+'" '+(collapsed.has(layer)?'':'open')+'>'+branch('layer',layer,layer+' · '+label,group.length)+[...new Set(group.map(i=>alias(F[i])))].map(id=>{const variants=group.filter(i=>alias(F[i])===id);return '<details class="factor-variant" data-branch="'+id+'" '+(collapsed.has(id)?'':'open')+'>'+branch('definition',id,id.split('_')[0]+' · '+name(F[variants[0]]),variants.length)+variants.map(factorButton).join('')+'</details>'}).join('')+'</details>'}).join('');
 $('factor-list').querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>{current=+b.dataset.index;selection={kind:'leaf',key:current};refresh()});
 $('factor-list').querySelectorAll('.tree-title').forEach(b=>b.onclick=e=>{e.preventDefault();selection={kind:b.dataset.kind,key:b.dataset.key};refresh()});
 $('factor-list').querySelectorAll('details').forEach(el=>{const b=el.querySelector(':scope > summary .tree-toggle'),sync=()=>{b.setAttribute('aria-expanded',String(el.open));el.open?collapsed.delete(el.dataset.branch):collapsed.add(el.dataset.branch)};sync();b.onclick=e=>{e.preventDefault();e.stopPropagation();el.open=!el.open;sync()};el.ontoggle=()=>{if(el.isConnected)sync()}});
 let last='';const rows=cs.map(i=>{const layer=F[i].metadata.layer,head=!flat&&last!==layer?'<tr class="ranking-group"><th colspan="9">'+esc(layers[layer])+'</th></tr>':'';last=layer;return head+'<tr>'+rankingCells(i,detailPeriod).map(v=>'<td>'+v+'</td>').join('')+'</tr>'});$('ranking-table').innerHTML='<table><thead><tr>'+rankingHeaders.map(v=>'<th>'+v+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>';bindRanking($('ranking-table'),detailPeriod);
 $('ranking-note').textContent=periodName(D.periods[detailPeriod])+' · '+cs.length+' 个方向因子 · '+(flat?'全部混排':'保留研究逻辑与定义分组，Buy / Sell 相邻显示')+'。表格、导航与下载共用筛选及排序。';}
function linePlot(series,{label='',unit='',dates=[],bars=false,intervals=null}={}){
 const width=780,height=280,left=65,right=18,top=25,bottom=48,n=Math.max(...series.map(s=>s.values.length),1),all=series.flatMap(s=>s.values).filter(Number.isFinite);if(intervals)all.push(...intervals.flat().filter(Number.isFinite));
 if(!all.length)return '<p class="empty">该区间没有可绘制的有效观察。</p>';let lo=Math.min(0,...all),hi=Math.max(0,...all);if(lo===hi){lo-=.01;hi+=.01}const pad=(hi-lo)*.1;lo-=pad;hi+=pad;
 const sx=i=>left+(width-left-right)*(i+.5)/n,sy=y=>top+(height-top-bottom)*(hi-y)/(hi-lo);let result='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+esc(label)+'"><rect width="780" height="280" fill="white"/>';
 for(let j=0;j<5;j++){const v=lo+(hi-lo)*j/4,y=sy(v);result+='<line x1="'+left+'" x2="'+(width-right)+'" y1="'+y+'" y2="'+y+'" stroke="#e2e6df"/><text x="'+(left-8)+'" y="'+(y+4)+'" text-anchor="end" font-size="11" fill="#61716f">'+fmt(v,unit==='bp'?2:3)+'</text>'}
 result+='<line x1="'+left+'" x2="'+(width-right)+'" y1="'+sy(0)+'" y2="'+sy(0)+'" stroke="#a6b5ae"/>';
 series.forEach(s=>{let path='',pen=false;s.values.forEach((v,i)=>{if(!Number.isFinite(v)){pen=false;return}const x=sx(i),y=sy(v);if(bars)result+='<rect x="'+(x-(width-left-right)/n*.4)+'" y="'+Math.min(y,sy(0))+'" width="'+(width-left-right)/n*.8+'" height="'+Math.max(.3,Math.abs(y-sy(0)))+'" fill="'+s.color+'"><title>'+esc(s.name)+' '+esc(dates[i]??i+1)+': '+fmt(v,6)+'</title></rect>';else{path+=(pen?'L':'M')+x.toFixed(2)+','+y.toFixed(2);pen=true}
 if(intervals&&Number.isFinite(intervals[i][0])&&Number.isFinite(intervals[i][1]))result+='<line x1="'+x+'" x2="'+x+'" y1="'+sy(intervals[i][0])+'" y2="'+sy(intervals[i][1])+'" stroke="'+s.color+'"/><circle cx="'+x+'" cy="'+y+'" r="3" fill="'+s.color+'"><title>G'+(i+1)+': '+fmt(v,5)+' '+unit+'</title></circle>'});if(!bars)result+='<path d="'+path+'" fill="none" stroke="'+s.color+'" stroke-width="'+(s.width||1.4)+'" opacity="'+(s.opacity||1)+'"/>'});
 for(const i of [...new Set([0,Math.floor((n-1)/2),n-1])])result+='<text x="'+sx(i)+'" y="'+(height-14)+'" text-anchor="middle" font-size="11" fill="#61716f">'+esc(dates[i]??i+1)+'</text>';
 return result+'<text x="'+left+'" y="14" font-size="11" fill="#61716f">'+esc(label)+(unit?' / '+unit:'')+'</text></svg><div class="legend">'+series.map(s=>'<span><i class="dot" style="background:'+s.color+'"></i>'+esc(s.name)+'</span>').join('')+'</div>';}
function chart(label,content){return '<figure class="plot-card"><h4>'+esc(label)+'</h4><button class="figure-button" data-zoom="'+esc(label)+'" aria-label="放大 '+esc(label)+'">'+content+'</button><figcaption class="chart-note">点击图表放大并下载 SVG。</figcaption></figure>'}
const rolling=v=>v.map((_,i)=>{const a=v.slice(Math.max(0,i-19),i+1).filter(Number.isFinite);return a.length>=10?a.reduce((s,x)=>s+x,0)/a.length:null});
const cumulative=v=>{let sum=0;return v.map(x=>Number.isFinite(x)?sum+=x:null)};
let densitySerial=0;
function densitySVG(d,fit){const clip='density-clip-'+(++densitySerial),w=780,h=400,l=76,r=28,t=32,b=55,[xmin,xmax,ymin,ymax]=d.bounds,sx=x=>l+(x-xmin)/(xmax-xmin)*(w-l-r),sy=y=>t+(ymax-y)/(ymax-ymin)*(h-t-b),max=Math.max(...d.cells.map(c=>c[2]),1),bw=(w-l-r)/d.bins[0],bh=(h-t-b)/d.bins[1];let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+w+' '+h+'" role="img" aria-label="全部成对样本散点密度"><rect width="780" height="400" fill="white"/><defs><clipPath id="'+clip+'"><rect x="'+l+'" y="'+t+'" width="'+(w-l-r)+'" height="'+(h-t-b)+'"/></clipPath></defs><g clip-path="url(#'+clip+')">';
 for(const [a,b,count] of d.cells){const opacity=.15+.85*Math.log1p(count)/Math.log1p(max);svg+='<rect x="'+(l+a*bw)+'" y="'+(t+(d.bins[1]-1-b)*bh)+'" width="'+(bw+.2)+'" height="'+(bh+.2)+'" fill="#087b78" opacity="'+opacity+'"><title>'+count+' 个股票日</title></rect>'}
 if(fit.status==='complete')svg+='<line x1="'+sx(xmin)+'" x2="'+sx(xmax)+'" y1="'+sy(fit.alpha+fit.beta*xmin)+'" y2="'+sy(fit.alpha+fit.beta*xmax)+'" stroke="#b24f35" stroke-width="2"/>';
 svg+='</g>';for(let i=0;i<5;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;svg+='<text x="'+sx(x)+'" y="'+(h-b+22)+'" text-anchor="middle" font-size="11" fill="#61716f">'+fmt(x,4)+'</text><text x="'+(l-8)+'" y="'+(sy(y)+4)+'" text-anchor="end" font-size="11" fill="#61716f">'+fmt(y*1e4,2)+'</text>'}return svg+'<text x="'+l+'" y="17" font-size="12" fill="#61716f">收益 / bp · 颜色深度为 log(1 + 股票日计数)</text><text x="390" y="393" text-anchor="middle" font-size="12" fill="#61716f">因子原值</text></svg>';}
function applyTab(){document.querySelectorAll('#detail-cards [data-tab]').forEach(b=>{const on=b.dataset.tab===tab;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1});document.querySelectorAll('#detail-cards .detail-pane').forEach(p=>p.hidden=p.dataset.key!=='pane-'+tab)}
function bindCharts(root,f){root.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{const svg=b.querySelector('svg');if(!svg)return;if(zoomURL)URL.revokeObjectURL(zoomURL);zoomURL=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}));$('figure-title').textContent=title(f)+' / '+b.dataset.zoom;$('figure-image').src=zoomURL;$('figure-download').href=zoomURL;$('figure-download').download=alias(f)+'-'+f.metadata.projection+'-'+b.dataset.zoom+'.svg';$('figure-dialog').showModal()})}
async function drawFactorDetail(root,index,version){const get=key=>root.querySelector('[data-key="'+key+'"]');let f;try{f=await loadFactor(index)}catch(error){get('factor-title').textContent=error.message;return}if(version!==detailVersion||!root.isConnected)return;F[index]=f;const m=f.metadata,s=f.periods[detailPeriod],dist=f.distribution,extra=f.details,def=definition(f),p=D.periods[detailPeriod],indices=D.dates.map((_,i)=>i).filter(i=>D.dates[i]>=p.start&&D.dates[i]<=p.end),paired=indices.reduce((n,i)=>n+f.daily_health[i][3],0);
 get('factor-title').textContent=title(f)+(f.diagnostic?'（诊断指标）':'');get('factor-identity').textContent=m.factor_id;get('detail-period-label').textContent='评价区间：'+periodName(p);
 const metrics=[['IC',fmt(s.ic[0][0],6)],['Rank IC',fmt(s.ic[1][0],6)],['ICIR · 不年化',fmt(s.ic[1][5],4)],['Rank IC · NW t',fmt(s.ic[1][3],3)],['G10−G1 · bp',fmt(bp(s.spread[0][0]),3)],['组差 · NW t',fmt(s.spread[0][3],3)]];
 get('detail-metrics').innerHTML=metrics.map(([k,v])=>'<div class="metric"><b>'+v+'</b><span>'+k+'</span></div>').join('');get('detail-coverage').textContent=periodName(p)+'：'+s.ic[1][4]+' 个有效 IC 日，成对样本 '+comma(paired)+' 股票日。全期原值有限 '+comma(dist.finite)+'，非有限 '+comma(dist.rows-dist.finite)+'，恰为零 '+comma(dist.zero)+'，常数或无成对样本日 '+dist.constant_days+'。';
 get('download-factor').onclick=()=>save(JSON.stringify({dates:D.dates,period_definitions:D.periods,statistics_schema:D.statistics_schema,label:D.label,factor:f},null,2),alias(f)+'-'+m.projection+'.evaluation.json');
 const daily=f.daily_ic.map((_,j)=>({date:D.dates[j],ic:f.daily_ic[j][0],rank_ic:f.daily_ic[j][1],rows:f.daily_health[j][0],finite:f.daily_health[j][1],zero:f.daily_health[j][2],paired:f.daily_health[j][3],unique:f.daily_health[j][4],spread:f.daily_spread[j][0]})),icRoll=rolling(daily.map(r=>r.ic)),rankRoll=rolling(daily.map(r=>r.rank_ic)),icCum=cumulative(daily.map(r=>r.ic)),rankCum=cumulative(daily.map(r=>r.rank_ic));
 daily.forEach((r,j)=>Object.assign(r,{ic_rolling20:icRoll[j],rank_ic_rolling20:rankRoll[j],ic_cumulative:icCum[j],rank_ic_cumulative:rankCum[j]}));
 get('pane-ic').innerHTML='<h4>日度相关与累计轨迹 · 全部 601 日</h4><div class="plot-grid">'+['IC','Rank IC'].map((n,j)=>chart(n+' · 日度与滚动均值',linePlot([{name:'每日相关',color:colors[j],opacity:.3,values:f.daily_ic.map(r=>r[j])},{name:'20 日滚动均值',color:colors[j],width:2,values:j?rankRoll:icRoll}],{label:n,dates:D.dates}))).join('')+['IC','Rank IC'].map((n,j)=>chart('累计 '+n,linePlot([{name:'累计 '+n,color:colors[j],values:j?rankCum:icCum}],{label:'累计 '+n,dates:D.dates}))).join('')+'</div><p class="chart-note">图表固定展示全部 601 日。滚动均值至少需要 10 个有效日；累计 IC 是相关系数之和，不是资金净值。明细日期只筛选下表与 CSV，累计列保留全历史起点。</p><h4>日度明细</h4><div class="controls date-controls"><label>起始日期<input data-key="date-start" type="date"></label><label>结束日期<input data-key="date-end" type="date"></label><button data-key="download-daily">下载筛选后日度 CSV</button><span data-key="daily-count" class="small"></span></div><div data-key="daily-table" class="table-scroll daily-table"></div>';
 const dailyRows=()=>daily.filter(r=>(!dateRange.start||r.date>=dateRange.start)&&(!dateRange.end||r.date<=dateRange.end));
 function drawDaily(){if(!root.isConnected)return;get('date-start').value=dateRange.start;get('date-end').value=dateRange.end;const rows=dailyRows();get('daily-count').textContent=dateRange.start&&dateRange.end&&dateRange.start>dateRange.end?'起始日期晚于结束日期，请调整。':rows.length+' 日 · 日期在当前因子间同步';get('download-daily').disabled=!rows.length;get('daily-table').innerHTML=table(['日期','IC','Rank IC','20 日 IC','20 日 Rank','累计 IC','累计 Rank','G10−G1 bp','成对数','有限数','零值数','不同值数'],rows.map(r=>[r.date,fmt(r.ic,6),fmt(r.rank_ic,6),fmt(r.ic_rolling20,6),fmt(r.rank_ic_rolling20,6),fmt(r.ic_cumulative,6),fmt(r.rank_ic_cumulative,6),fmt(bp(r.spread),3),r.paired,r.finite,r.zero,r.unique]))}
 dailyRefresh.add(drawDaily);drawDaily();for(const [key,field] of [['date-start','start'],['date-end','end']])get(key).onchange=()=>{dateRange[field]=get(key).value;dailyRefresh.forEach(fn=>fn())};get('download-daily').onclick=()=>{const rows=dailyRows(),keys=Object.keys(daily[0]);save(csv([keys,...rows.map(r=>keys.map(k=>r[k]))]),alias(f)+'-'+m.projection+'-'+dateRange.start+'-'+dateRange.end+'-daily.csv','text/csv;charset=utf-8')};
 const months=D.periods.map((p,i)=>({p,i})).filter(({p})=>/^\d{4}-\d{2}$/.test(p.id));get('pane-monthly').innerHTML='<h4>全部 601 日 · 30 个月的相关表现</h4><div class="plot-grid">'+['IC','Rank IC'].map((n,j)=>chart('月度 '+n,linePlot([{name:'月度日均 '+n,color:colors[j],values:months.map(({i})=>f.periods[i].ic[j][0])}],{label:n,dates:months.map(({p})=>p.id),bars:true}))).join('')+'</div><p class="chart-note">各月先计算每日横截面相关，再对有效日等权；颜色不表示显著性。评价区间不裁剪全历史月度图。</p><div class="table-scroll">'+table(['月份','IC','Rank IC','ICIR','Rank NW t','有效日'],months.map(({p,i})=>[p.id,fmt(f.periods[i].ic[0][0],6),fmt(f.periods[i].ic[1][0],6),fmt(f.periods[i].ic[1][5],3),fmt(f.periods[i].ic[1][3],3),f.periods[i].ic[1][4]]))+'</div>';
 let groupCharts='';for(const [k,offset] of [[10,0],[40,10]])for(const [kind,j] of [['毛收益',0],['超额收益',1]]){const g=s.groups.slice(offset,offset+k).map(r=>r[j]),values=g.map(r=>bp(r[0])),intervals=g.map(r=>Number.isFinite(r[0])&&Number.isFinite(r[1])?[bp(r[0]-2*r[1]),bp(r[0]+2*r[1])]:[null,null]);groupCharts+=chart(k+' 组 · '+kind,linePlot([{name:kind,color:colors[j],values}],{label:'日度等权均值 ± 2 普通日度 SE',unit:'bp',intervals}))}
 const diagnostics=extra.group_diagnostics[detailPeriod],mu=s.groups.slice(0,10).map(g=>bp(g[0][0])),within=diagnostics.map((d,i)=>Number.isFinite(d.typical_within_std)&&Number.isFinite(mu[i])?[mu[i]-d.typical_within_std*1e4,mu[i]+d.typical_within_std*1e4]:[null,null]),nw=s.groups.slice(0,10).map(g=>Number.isFinite(g[0][0])&&Number.isFinite(g[0][2])?[bp(g[0][0]-1.96*g[0][2]),bp(g[0][0]+1.96*g[0][2])]:[null,null]);
 get('pane-groups').innerHTML='<h4>'+esc(periodName(p))+' · 分组收益</h4><div class="plot-grid">'+chart('十分组毛收益均值',linePlot([{name:'毛收益',color:colors[1],values:mu}],{label:'因子原值由低到高',unit:'bp',bars:true}))+chart('均值 ± 典型日内组内标准差',linePlot([{name:'组内离散尺度',color:colors[1],values:mu}],{label:'不表示均值置信区间',unit:'bp',intervals:within}))+chart('均值 ± 1.96 × NW 标准误',linePlot([{name:'均值近似 95% NW 区间',color:colors[0],values:mu}],{label:'Bartlett lag 1',unit:'bp',intervals:nw}))+'</div><p>G10−G1 = '+fmt(bp(s.spread[0][0]),3)+' bp；配对近似 95% NW 区间 ['+fmt(Number.isFinite(s.spread[0][2])?bp(s.spread[0][0]-1.96*s.spread[0][2]):null,3)+', '+fmt(Number.isFinite(s.spread[0][2])?bp(s.spread[0][0]+1.96*s.spread[0][2]):null,3)+'] bp。最高 20%−最低 20%：'+fmt(bp(s.spread[2][0]),3)+' bp。</p><div class="table-scroll">'+table(['组','毛收益 bp','超额收益 bp','收益百分位 %','日内中位数 bp','缩尾均值 bp','尾部贡献 bp','正收益 %','有效日','股票日','NW t'],s.groups.slice(0,10).map((g,i)=>{const d=diagnostics[i];return ['G'+(i+1),fmt(bp(g[0][0]),3),fmt(bp(g[1][0]),3),fmt(Number.isFinite(d.return_percentile)?d.return_percentile*100:null,3),fmt(bp(d.median_return),3),fmt(bp(d.winsorized_mean),3),fmt(bp(d.tail_contribution),3),fmt(Number.isFinite(d.positive_fraction)?d.positive_fraction*100:null,2),g[0][4],comma(d.stock_days),fmt(g[0][3],3)]}))+'</div><p class="chart-note">组内先按股票等权，再对非空有效日等权。收益百分位、中位数和缩尾均值均先按日统计；缩尾阈值是每日成对收益 P1/P99，尾部贡献为原均值减缩尾均值。典型组内标准差为日内总体方差日均值的平方根；NW 区间描述组日均收益的不确定性，两者不同。并列值同组，空组不填零；收益分组不沿用 IC 的至少 30 个样本门槛。</p><button data-key="download-groups">下载所选区间完整分组诊断 CSV</button><details><summary>10 / 40 组毛收益与超额收益 · 普通日度 SE</summary><div class="plot-grid">'+groupCharts+'</div><div class="table-scroll">'+table(['分组数','组','毛收益 bp','超额收益 bp','有效日','毛收益 NW t'],s.groups.map((g,i)=>[i<10?10:40,'G'+(i<10?i+1:i-9),fmt(bp(g[0][0]),3),fmt(bp(g[1][0]),3),g[0][4],fmt(g[0][3],3)]))+'</div><p>40 组 G40−G1：'+fmt(bp(s.spread[1][0]),3)+' bp。误差线为均值 ± 2 普通日度 SE；与上方 NW 区间分开表示。</p></details>';
 get('download-groups').onclick=()=>{const keys=['group','mean_raw_return','mean_excess_return','ordinary_se','nw_se_lag1','nw_t','return_valid_days',...Object.keys(diagnostics[0])];save(csv([keys,...diagnostics.map((d,i)=>[i+1,s.groups[i][0][0],s.groups[i][1][0],s.groups[i][0][1],s.groups[i][0][2],s.groups[i][0][3],s.groups[i][0][4],...Object.values(d)])]),alias(f)+'-'+m.projection+'-'+p.id+'-group-diagnostics.csv','text/csv;charset=utf-8')};
 const fit=extra.ols;get('pane-scatter').innerHTML='<h4>因子原值与同日收益 · 全部 601 日</h4>'+(fit.status==='complete'?'<p class="fit-equation">收益（bp） = '+fmt(bp(fit.alpha),6)+(fit.beta>=0?' + ':' − ')+fmt(Math.abs(fit.beta)*1e4,6)+' × 因子原值</p>':'<p>因子原值没有足够的变化，OLS 无法识别斜率。</p>')+'<p>拟合 '+comma(fit.n)+' 股票日；R²='+fmt(fit.r_squared,8)+'，汇集 Pearson r='+fmt(fit.pooled_r,6)+'，RMSE='+fmt(bp(fit.rmse),3)+' bp。</p>'+(extra.scatter.full?chart('全部成对样本 · 散点密度',densitySVG(extra.scatter.full,fit))+chart('P1 / P99 坐标放大 · 同一完整样本拟合',densitySVG(extra.scatter.zoom,fit))+'<p class="chart-note">全范围图中全部 '+comma(extra.scatter.full.included)+' 个真实成对样本进入 128 × 96 网格，不抽样；重叠点用计数深度表示。放大图仅改变坐标范围，框内 '+comma(extra.scatter.zoom.included)+'、框外 '+comma(extra.scatter.zoom.outside)+' 个股票日。OLS 始终使用全部成对样本，不截尾。</p>':'')+'<p class="chart-note">模型包含截距，每个股票日等权。汇集相关与日均横截面 IC 口径不同；同股和同日的观测存在依赖，不报告假设观测独立的 OLS t 或 p。评价区间不改变全期拟合。</p><button data-key="download-ols">下载此因子 OLS JSON</button>';get('download-ols').onclick=()=>save(JSON.stringify({formal_column:m.factor_id,period:'full',...fit},null,2),alias(f)+'-'+m.projection+'-full-ols.json');
 const domain=m.domain,binDates=f.shape.map((_,i)=>fmt(domain[0]+(i+.5)*(domain[1]-domain[0])/100,3)),distribution=extra.distribution;
 get('pane-shape').innerHTML='<h4>因子原值分布 · 全部 601 日</h4>'+chart('全部有限因子值分布',linePlot([{name:'股票日计数',color:colors[1],values:f.shape.map(b=>b.count)}],{label:'100 个固定定义域等宽箱',dates:binDates,bars:true}))+'<div class="table-scroll">'+table(['统计','值'],[['有限数',comma(dist.finite)],['非有限数',comma(dist.rows-dist.finite)],['零值数',comma(dist.zero)],['均值',fmt(distribution.mean,8)],['标准差',fmt(distribution.std,8)],...Object.entries(distribution.quantiles).map(([k,v])=>['分位 '+k,fmt(v,8)])])+'</div>'+chart('分箱收益 · 全期日度等权',linePlot([{name:'毛收益',color:colors[1],values:f.shape.map(b=>bp(b.raw[0]))},{name:'超额收益',color:colors[0],values:f.shape.map(b=>bp(b.excess[0]))}],{label:'因子值分箱中心',unit:'bp',dates:binDates}))+'<p class="chart-note">分位数从全部有限原值精确计算，缺失值不填零。定义域 ['+domain.join(', ')+']；下溢 '+comma(dist.under)+'、上溢 '+comma(dist.over)+'，未裁剪。固定定义域箱可比较稀疏度，分箱收益可能来自不同股票与日期；区间不改变全期分布。</p>';
 get('pane-periods').innerHTML='<p>全期、年度、季度和月度是嵌套区间，不能将这些行当成独立样本。</p><div class="table-scroll">'+table(['区间','IC','Rank IC','ICIR','Rank NW t','有效日','G10−G1 bp','组差 NW t'],D.periods.map((p,i)=>{const r=f.periods[i];return [esc(periodName(p)),fmt(r.ic[0][0],6),fmt(r.ic[1][0],6),fmt(r.ic[1][5],3),fmt(r.ic[1][3],3),r.ic[1][4],fmt(bp(r.spread[0][0]),3),fmt(r.spread[0][3],3)]}))+'</div><p class="chart-note">ICIR = 日均 Rank IC / 日度 Rank IC 样本标准差，未年化；NW t 采用 Bartlett lag 1，对有效日期序列计算。</p>';
 const records=[['层次',m.layer+' · '+layers[m.layer]],['注册身份',m.kind],['逻辑编号',m.logical_factor_id],['来源评分',m.source_scorer],['评分规格',m.source_specification_id||'—'],['情境 / 组件',m.context||m.component_id||'—'],['方向',sides[m.projection]],['分母',m.denominator],['全期股票日',comma(dist.rows)],['有限值覆盖',fmt(dist.finite/dist.rows*100,2)+'%'],['零值 / 全部股票日',fmt(dist.zero/dist.rows*100,2)+'%'],['全期成对股票日',comma(dist.pairs)],['成对不同取值不超过 1 的天数',dist.constant_days]];
 get('pane-definition').innerHTML='<h4>正式列名</h4><code>'+esc(m.factor_id)+'</code><p>'+esc(def.description||'按冻结注册表与来源评分规格构造。')+'</p>'+(def.base_logic?'<p>来源逻辑：<code>'+esc(def.base_logic)+'</code></p>':'')+'<div class="formula">'+esc(def.formula||'股票日内方向贡献按冻结定义聚合；分母为全部有效去重新委托数。')+'</div><div class="table-scroll">'+table(['字段','身份 / 覆盖'],records.map(r=>r.map(esc)))+'</div><h4>评价口径与复算</h4><p>窗口 [09:30,09:35)，方向和冻结 R19 参数保持原定义。日度 IC 至少使用 30 个成对股票；常数截面不生成有效 IC，缺失不填零。日度相关、分组收益及分期统计直接读取原评价；补充分组计数与均值逐日逐列对照一致，OLS 和原值分位数使用完整历史样本。</p><p class="chart-note">原 IC 独立抽查为每日一列，共 601 个因子日；不将抽查描述为全部 173,088 个因子日独立复算。诊断列与正式因子分开标记。</p>'+(f.diagnostic?'<p class="status">本列是市场行为诊断指标，未计入正式 284 列。</p>':'');
 root.querySelectorAll('[data-tab]').forEach((b,i,buttons)=>{const pane=get('pane-'+b.dataset.tab),id='factor-'+index+'-'+b.dataset.tab;b.id=id+'-tab';b.setAttribute('aria-controls',id);pane.id=id;pane.setAttribute('role','tabpanel');pane.setAttribute('aria-labelledby',b.id);b.onclick=()=>{tab=b.dataset.tab;applyTab()};b.onkeydown=e=>{const j=e.key==='ArrowRight'?(i+1)%buttons.length:e.key==='ArrowLeft'?(i+buttons.length-1)%buttons.length:e.key==='Home'?0:e.key==='End'?buttons.length-1:null;if(j!==null){e.preventDefault();tab=buttons[j].dataset.tab;applyTab();buttons[j].focus()}}});
 bindCharts(root,f);applyTab();root.dataset.ready='true';document.body.dataset.detailReady='true';}
function renderDetails(){const version=++detailVersion;observer?.disconnect();dailyRefresh.clear();document.body.dataset.detailReady='false';const cs=ordered().filter(inScope),label=selection.kind==='leaf'?title(F[current]):selection.kind==='definition'?name(F[cs[0]||current]):layers[selection.key];$('scope-summary').innerHTML='<h3>'+esc(label||'当前范围')+'</h3><p>'+periodName(D.periods[detailPeriod])+' · 当前范围 '+cs.length+' 个方向因子</p><p class="small">指标与分组诊断使用所选区间；日度图、月度图、原值分布和 OLS 展示全部 601 日。选择定义可对照 Buy / Sell，标签页和明细日期在当前显示因子间同步。'+(cs.length?'':'没有符合条件的因子，请调整或清空筛选。')+'</p>';$('detail-cards').replaceChildren();
 observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){observer.unobserve(entry.target);drawFactorDetail(entry.target,+entry.target.dataset.index,version)}}),{rootMargin:'500px'});
 let first=0;for(const id of [...new Set(cs.map(i=>alias(F[i])))]){const pair=cs.filter(i=>alias(F[i])===id),wrap=document.createElement('div');wrap.className='detail-pair'+(pair.length===1?' single':'');$('detail-cards').append(wrap);for(const i of pair){const root=$('detail-template').content.firstElementChild.cloneNode(true);root.dataset.index=i;root.querySelector('[data-key="factor-title"]').textContent='正在加载 '+title(F[i])+'…';wrap.append(root);if(first++<2)drawFactorDetail(root,i,version);else observer.observe(root)}}
}
function refresh(){const cs=ordered();if(cs.length&&!cs.some(inScope)){current=cs[0];selection={kind:'leaf',key:current}}renderList();renderDetails()}
function resetFilters(draw=true){for(const id of ['layer-filter','family-filter','side-filter','factor-scope'])$(id).value='all';$('factor-search').value='';$('view-mode').value='all';$('factor-arrangement').value='grouped';$('factor-sort').value='id';if(draw)refresh()}
for(const id of ['global-period','result-scope','result-sort'])$(id).onchange=renderResults;$('result-search').oninput=renderResults;
for(const id of ['layer-filter','family-filter','factor-scope','factor-sort','factor-arrangement'])$(id).onchange=refresh;$('factor-search').oninput=refresh;
$('view-mode').onchange=()=>{if($('view-mode').value==='separate'&&$('side-filter').value==='all')$('side-filter').value='buy';refresh()};$('side-filter').onchange=()=>{$('view-mode').value=$('side-filter').value==='all'?'all':'separate';refresh()};
$('detail-period').onchange=()=>{detailPeriod=+$('detail-period').value;dateRange={start:D.periods[detailPeriod].start,end:D.periods[detailPeriod].end};refresh()};$('reset-filters').onclick=()=>resetFilters();
for(const [id,open] of [['expand-tree',true],['collapse-tree',false]])$(id).onclick=()=>{document.querySelectorAll('#factor-list details').forEach(el=>{el.open=open;open?collapsed.delete(el.dataset.branch):collapsed.add(el.dataset.branch);el.querySelector(':scope > summary .tree-toggle').setAttribute('aria-expanded',String(open))})};
function summaryCSV(indexes,p){return csv([['formal_column','definition','diagnostic','side','period','IC','Rank_IC','ICIR','Rank_NW_t','G10_minus_G1_return','spread_NW_t','valid_days'],...indexes.map(i=>{const f=F[i],s=f.periods[p];return [f.metadata.factor_id,name(f),f.diagnostic,f.metadata.projection,D.periods[p].id,s.ic[0][0],s.ic[1][0],s.ic[1][5],s.ic[1][3],s.spread[0][0],s.spread[0][3],s.ic[1][4]]})])}
$('download-summary').onclick=()=>{const p=+$('global-period').value;save(summaryCSV(rowsForResults(),p),'rawbank-'+D.periods[p].id+'.csv','text/csv;charset=utf-8')};$('download-explorer').onclick=()=>save(summaryCSV(ordered(),detailPeriod),'rawbank-filtered-'+D.periods[detailPeriod].id+'.csv','text/csv;charset=utf-8');
$('download-proof').onclick=()=>save(JSON.stringify(P,null,2),'rawbank-evaluation-result.json');$('download-alignment').onclick=()=>save(csv([['date','stock_days','valid_label_stock_days'],...D.label_alignment.map(r=>[r.date,r.rows,r.valid_labels])]),'rawbank-label-alignment.csv','text/csv;charset=utf-8');
$('figure-close').onclick=()=>$('figure-dialog').close();$('figure-dialog').addEventListener('click',e=>{if(e.target===$('figure-dialog'))$('figure-dialog').close()});
renderResults();refresh();document.body.dataset.ready='true';
})().catch(error=>{document.getElementById('result-note').textContent='评价数据加载失败：'+error.message;console.error(error)});
