const { chromium } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const out = path.join(__dirname, '../test-results/model-report-20260918');
  fs.mkdirSync(out, { recursive: true });
  const results = [];
  for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
    const page = await browser.newPage({ viewport });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://127.0.0.1:8019/content/daily/2026-09-18.show.html');
    await page.waitForFunction(() => window.__modelReportReady === true);
    assert.equal(await page.locator('figure').count(), 27);
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
    assert.equal(overflow, false, 'document must not overflow horizontally');
    await page.screenshot({ path: path.join(out, `hero-${viewport.width}.png`) });
    await page.locator('#deciles').screenshot({ path: path.join(out, `deciles-${viewport.width}.png`) });
    await page.locator('#ic-scatter').screenshot({ path: path.join(out, `scatter-${viewport.width}.png`) });
    await page.locator('.case-grid').screenshot({ path: path.join(out, `cases-${viewport.width}.png`) });
    await page.locator('#legs .enlarge').click();
    assert.equal(await page.locator('#chart-dialog').evaluate(el => el.open), true);
    assert.equal(await page.locator('#dialog-chart svg').count(), 1);
    await page.locator('#close-dialog').click();
    await page.getByText('检索完整 328 列映射', { exact: true }).click();
    await page.locator('#factor-search').fill('old__f97');
    assert.equal(await page.locator('#mapping tbody tr').count(), 0);
    await page.locator('#factor-search').fill('old__f96');
    assert.equal(await page.locator('#mapping tbody tr').count(), 2);
    await page.locator('#factor-search').fill('');
    assert.equal(await page.locator('#mapping tbody tr').count(), 328);
    const download = page.waitForEvent('download');
    await page.locator('#download-daily').click();
    const file = await download;
    await file.saveAs(path.join(out, `daily-${viewport.width}.csv`));
    assert.equal(fs.readFileSync(path.join(out, `daily-${viewport.width}.csv`), 'utf8').trim().split('\n').length, 177);
    assert.deepEqual(errors, []);
    results.push({ viewport, chartCount: 27, errors, documentOverflow: overflow, downloadRows: 176 });
    await page.close();
  }
  const dashboard = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const dashboardErrors = [];
  dashboard.on('pageerror', e => dashboardErrors.push(e.message));
  await dashboard.goto('http://127.0.0.1:8019/dist/#/daily/2026-09-18/show');
  await dashboard.waitForSelector('#daily-show-content iframe');
  const iframe = dashboard.locator('#daily-show-content iframe');
  assert.equal(await iframe.getAttribute('sandbox'), 'allow-scripts allow-downloads');
  const frame = await (await iframe.elementHandle()).contentFrame();
  await frame.waitForFunction(() => window.__modelReportReady === true);
  assert.equal(await frame.locator('figure').count(), 27);
  await dashboard.screenshot({ path: path.join(out, 'dashboard-1440.png') });
  await frame.locator('nav a[href="#explain"]').click();
  await frame.waitForFunction(() => location.hash === '#explain');
  assert.equal(dashboard.url(), 'http://127.0.0.1:8019/dist/#/daily/2026-09-18/show');
  const embeddedDownload = dashboard.waitForEvent('download');
  await frame.locator('#download-mapping').click();
  const mappingFile = await embeddedDownload;
  await mappingFile.saveAs(path.join(out, 'embedded-mapping.json'));
  assert.equal(JSON.parse(fs.readFileSync(path.join(out, 'embedded-mapping.json'), 'utf8')).length, 328);
  assert.deepEqual(dashboardErrors, []);
  results.push({ dashboardRoute: dashboard.url(), sandbox: 'allow-scripts allow-downloads', embeddedDownloadColumns: 328, errors: dashboardErrors });
  await browser.close();
  fs.writeFileSync(path.join(out, 'browser-checks.json'), JSON.stringify(results, null, 2));
  console.log(JSON.stringify(results, null, 2));
})().catch(error => { console.error(error); process.exitCode = 1; });
