const { chromium }=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
let browser;
(async()=>{
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://dashboard.test/**',route=>{const pathname=new URL(route.request().url()).pathname;const asset=path.join(root,'dist',pathname.slice(1));if(route.request().isNavigationRequest()&&pathname==='/')return route.fulfill({contentType:'text/html',body:'<div id="report"></div><style>iframe{width:100%;height:940px;border:0}</style>'});if(fs.existsSync(asset)&&fs.statSync(asset).isFile())return route.fulfill({path:asset,contentType:pathname.endsWith('.js')?'text/javascript':undefined});return route.fulfill({status:404,body:'missing asset'})});
 await page.goto('https://dashboard.test/#/daily/2026-09-16/show');
 await page.evaluate(fs.readFileSync(path.join(root,'site/js/router.js'),'utf8'));
 await page.evaluate(fs.readFileSync(path.join(root,'site/js/daily.js'),'utf8'));
 const manifest=JSON.parse(fs.readFileSync(path.join(root,'dist/manifest.json'),'utf8')),item=manifest.daily.find(r=>r.date==='2026-09-16');
 await page.evaluate(async item=>{window.DailyView.showEl=document.querySelector('#report');window.DailyView.app=window.DashboardApp;await window.DailyView.renderShow(item)},item);
 assert.equal(await page.locator('iframe').getAttribute('sandbox'),'allow-scripts allow-downloads');
 const frame=page.frames().find(f=>f.parentFrame());await frame.waitForSelector('body[data-detail-ready="true"]',{timeout:60000});
 assert.equal(await frame.locator('#factor-list .factor-item').count(),288);assert.equal(await frame.locator('#all-results tbody tr').count(),284);
 const cards=()=>frame.locator('#detail-cards .detail');
 const ready=()=>frame.waitForFunction(()=>[...document.querySelectorAll('#detail-cards .detail')].every(c=>c.dataset.ready==='true'));
 const title=()=>cards().first().locator('[data-key="factor-title"]');
 assert.match(await title().innerText(),/深度耗尽后补量/);
 await frame.selectOption('#view-mode','separate');await frame.selectOption('#side-filter','sell');assert.equal(await frame.locator('#factor-list .factor-item').count(),142);
 await frame.selectOption('#side-filter','total');assert.equal(await frame.locator('#factor-list .factor-item').count(),4);
 await frame.locator('#factor-list .factor-item').last().click();await ready();assert.match(await title().innerText(),/诊断指标/);
 await frame.selectOption('#view-mode','all');await frame.selectOption('#layer-filter','L5');assert.equal(await frame.locator('#factor-list .factor-item').count(),66);
 await frame.locator('#factor-list .factor-item').first().click();await ready();
 await frame.selectOption('#detail-period','43');await ready();await cards().first().locator('[data-tab="groups"]').click();assert.equal(await cards().first().locator('[data-key="pane-groups"] svg').count(),7);
 await cards().first().locator('[data-tab="periods"]').click();assert.equal(await cards().first().locator('[data-key="pane-periods"] tbody tr').count(),44);
 await cards().first().locator('[data-tab="monthly"]').click();assert.equal(await cards().first().locator('[data-key="pane-monthly"] svg').count(),2);assert.equal(await cards().first().locator('[data-key="pane-monthly"] tbody tr').count(),30);
 await cards().first().locator('[data-tab="shape"]').click();assert.equal(await cards().first().locator('[data-key="pane-shape"] svg').count(),2);
 await cards().first().locator('[data-tab="scatter"]').click();assert.equal(await cards().first().locator('[data-key="pane-scatter"] svg').count(),2);
 await frame.selectOption('#result-scope','diagnostic');assert.equal(await frame.locator('#all-results tbody tr').count(),4);
 await frame.selectOption('#global-period','1');await frame.selectOption('#result-scope','all');assert.equal(await frame.locator('#all-results tbody tr').count(),288);
 for(const id of ['definition','contract','results','factors','evidence']){await frame.locator('nav a[href="#'+id+'"]').click();assert.equal(frame.url(),'about:srcdoc#'+id)}
 await frame.locator('#reset-filters').click();await frame.selectOption('#result-scope','formal');await frame.locator('nav a[href="#factors"]').click();
 const family='f100_maker_depletion_refill';await frame.selectOption('#family-filter',family);assert.equal(await frame.locator('#factor-list .factor-item').count(),2);
 await frame.locator('.tree-title[data-kind="definition"][data-key="'+family+'"]').click();await ready();assert.equal(await cards().count(),2);
 await frame.selectOption('#detail-period','0');await ready();
 await cards().first().locator('[data-tab="ic"]').click();assert.equal(await cards().first().locator('[data-key="pane-ic"] svg').count(),4);
 await cards().first().locator('[data-key="date-start"]').fill('2025-01-01');await cards().first().locator('[data-key="date-start"]').dispatchEvent('change');
 assert.equal(await cards().last().locator('[data-key="date-start"]').inputValue(),'2025-01-01');
 const dailyEvent=page.waitForEvent('download');await cards().first().locator('[data-key="download-daily"]').click();const dailyDownload=await dailyEvent,dailyCSV=fs.readFileSync(await dailyDownload.path(),'utf8');assert.match(dailyCSV,/ic_cumulative/);assert.doesNotMatch(dailyCSV,/2024-01-02/);
 await cards().first().locator('[data-tab="scatter"]').click();assert.equal(await cards().last().locator('[data-tab="scatter"]').getAttribute('aria-selected'),'true');
 await cards().first().locator('[data-key="pane-scatter"] [data-zoom]').first().click();assert.equal(await frame.locator('#figure-dialog').isVisible(),true);const svgEvent=page.waitForEvent('download');await frame.locator('#figure-download').click();const svgDownload=await svgEvent;assert.match(fs.readFileSync(await svgDownload.path(),'utf8'),/<svg/);await frame.locator('#figure-close').click();
 await frame.selectOption('#factor-arrangement','flat');await frame.selectOption('#factor-sort','rank_value');await ready();
 const visibleIndexes=await frame.locator('#factor-list .factor-item').evaluateAll(bs=>bs.map(b=>+b.dataset.index));const actualRanks=await frame.evaluate(indexes=>indexes.map(i=>window.rawbankReport.data.factors[i].periods[0].ic[1][0]),visibleIndexes);assert.ok(actualRanks[0]>=actualRanks[1]);
 const summaryEvent=page.waitForEvent('download');await frame.locator('#download-explorer').click();const summaryDownload=await summaryEvent,summaryCSV=fs.readFileSync(await summaryDownload.path(),'utf8');assert.equal(summaryCSV.trim().split('\r\n').length,3);assert.ok(summaryCSV.indexOf(await frame.evaluate(i=>window.rawbankReport.data.factors[i].metadata.factor_id,visibleIndexes[0]))<summaryCSV.indexOf(await frame.evaluate(i=>window.rawbankReport.data.factors[i].metadata.factor_id,visibleIndexes[1])));
 await frame.selectOption('#factor-arrangement','grouped');await ready();await frame.locator('#collapse-tree').click();assert.equal(await frame.locator('#factor-list details[open]').count(),0);await frame.locator('#expand-tree').click();assert.ok(await frame.locator('#factor-list details[open]').count()>0);
 await frame.locator('#factor-search').fill('does-not-exist');assert.equal(await frame.locator('#factor-list .factor-item').count(),0);assert.equal(await cards().count(),0);await frame.locator('#factor-search').fill('');await ready();
 await cards().first().locator('[data-tab="groups"]').click();const groupEvent=page.waitForEvent('download');await cards().first().locator('[data-key="download-groups"]').click();const groupDownload=await groupEvent;assert.equal(fs.readFileSync(await groupDownload.path(),'utf8').trim().split('\r\n').length,11);
 await frame.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';document.querySelector('#factors').scrollIntoView({behavior:'instant'})});
 const downloadEvent=page.waitForEvent('download');await cards().first().locator('[data-key="download-factor"]').click();const download=await downloadEvent;assert.match(download.suggestedFilename(),/evaluation\.json$/);const downloaded=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(downloaded.dates.length,601);assert.equal(downloaded.factor.periods.length,44);assert.equal(downloaded.factor.periods[0].groups.length,50);assert.equal(downloaded.factor.details.ols.n,downloaded.factor.distribution.pairs);assert.equal(downloaded.factor.details.scatter.full.included,downloaded.factor.distribution.pairs);
 assert.equal(await frame.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.length-new Set(ids).size}),0);
 await page.screenshot({path:process.argv[2]||path.join(root,'rawbank-report-desktop.png'),fullPage:false});
 await page.setViewportSize({width:390,height:844});await frame.evaluate(()=>{document.querySelector('#factors').scrollIntoView()});
 const overflow=await frame.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(overflow)console.log(await frame.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,nodes:[...document.querySelectorAll('*')].filter(e=>e.scrollWidth>e.clientWidth+2&&getComputedStyle(e).overflowX==='visible').slice(0,20).map(e=>({tag:e.tagName,id:e.id,cls:e.className,width:e.clientWidth,scroll:e.scrollWidth}))})));assert.equal(overflow,false);
 for(const key of ['ic','monthly','groups','scatter','shape','periods','definition']){await cards().first().locator('[data-tab="'+key+'"]').click();assert.equal(await frame.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'mobile '+key)}
 assert.deepEqual(errors,[]);assert.equal(page.url(),'https://dashboard.test/#/daily/2026-09-16/show');
 await page.evaluate(async()=>{window.DailyView.app={loadFragment:async()=>'<p>Report</p>',prepareIsolatedHtml:html=>html};await window.DailyView.renderShow({date:'default',title:'Default',show_type:'html',show_path:'unused'})});assert.equal(await page.locator('iframe').getAttribute('sandbox'),'allow-scripts');
 console.log('PASS: shared filters/order/CSV, grouped navigation, Buy/Sell comparison, daily dates, 30 monthly rows, 44 periods, full OLS/density, group diagnostics, zoom/download and mobile');await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1});
